- name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Kiwada
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
