name: Generate Snake

on:
  # Executa automaticamente todos os dias à meia-noite
  schedule:
    - cron: "0 0 * * *" 
  
  # Permite que você clique no botão "Run workflow" para testar agora
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Esta é a etapa que gera as imagens
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          # Ele pega automaticamente o usuário 'Kiwada'
          github_user_name: ${{ github.repository_owner }}
          
          # Aqui ele cria os dois arquivos que seu HTML pede
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Esta etapa envia as imagens para a branch 'output'
      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
